# This file was generated by GoReleaser. DO NOT EDIT.
cask "umbraco-cli" do
  version "0.4.13"

  on_macos do
    on_arm do
      sha256 "c7c29d2bce128c74bae51685d14818aab5f1da53ac390bb538c3e879ba385235"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "75dfcb6c4ca7d559a35d7533414fa2ed0b6892494d5d382b046b4336c0a924b2"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a77c3c9aa7b2f210a701d66805058610ba2e75f48359ac039c90f66e1f20531e"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b508acb7888343834be1770072f08f97144e29f9181d33ef19580bee4f6ff0e"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "umbraco-cli"
  desc "Command-line client for the Umbraco Management API"
  homepage "https://github.com/albanistrefi/umbraco_CLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umbraco"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umbraco"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The `umbraco` binary expects these environment variables:
      UMBRACO_BASE_URL
      UMBRACO_CLIENT_ID
      UMBRACO_CLIENT_SECRET

    The release archives are not notarized yet, so the cask clears the macOS
    quarantine attribute during installation.
  EOS
end
