# This file was generated by GoReleaser. DO NOT EDIT.
cask "umbraco-cli" do
  version "0.4.9"

  on_macos do
    on_intel do
      sha256 "5a7c68ec72ef530b07ae30b3f392250fd874159a6e7489abd74fac6e084a7f85"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fd7cbce84e5121a416929f36c388ce0a5ed24d488f798f7e212f3042a9526e88"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "121b8df9d34b24cbbe4bc22b23a65b0a5501641b1c97bd641afeccec51de45bd"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f33307957bc3a7c74d4e11952e82ebbd82e83226b88c526ffa4aaa41b04f972a"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "umbraco-cli"
  desc "Command-line client for the Umbraco Management API"
  homepage "https://github.com/albanistrefi/umbraco_CLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umbraco"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umbraco"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The `umbraco` binary expects these environment variables:
      UMBRACO_BASE_URL
      UMBRACO_CLIENT_ID
      UMBRACO_CLIENT_SECRET

    The release archives are not notarized yet, so the cask clears the macOS
    quarantine attribute during installation.
  EOS
end
