# This file was generated by GoReleaser. DO NOT EDIT.
cask "umbraco-cli" do
  version "0.4.10"

  on_macos do
    on_intel do
      sha256 "2cefd9bc3da489a2b5cdb3c48671bcbf5a9141a580eacca6e34c8beb57030b2e"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "63b51abb241b77bc6955046881a68c3248e04de07b9cad8cc94a83a602dab6a7"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b35ee81f5449d60999c0dae01afa216e8056ae2dd1023c96da6b149205f2dbe2"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "18719e5ddc13e5b5e7138e1a8c8c00ef124f45ba4409ac18bc66b28934bdd894"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "umbraco-cli"
  desc "Command-line client for the Umbraco Management API"
  homepage "https://github.com/albanistrefi/umbraco_CLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umbraco"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umbraco"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The `umbraco` binary expects these environment variables:
      UMBRACO_BASE_URL
      UMBRACO_CLIENT_ID
      UMBRACO_CLIENT_SECRET

    The release archives are not notarized yet, so the cask clears the macOS
    quarantine attribute during installation.
  EOS
end
